import { Feature } from "@/types/feature";

const featuresData: Feature[] = [
  {
    id: 1,
    icon: "/images/icon/icon-01.svg",
    title: "Generate PDF CVs",
    description:
      "We generate a CV on the template of your choice with a button to easily verify your credentials.",
  },
  {
    id: 2,
    icon: "/images/icon/icon-02.svg",
    title: "Ensure tracability of CVs",
    description:
      "Your diplomas, certificates and work experiences are trustable because published by your employer and your teaching institutions on our blockchain.",
  },
  {
    id: 3,
    icon: "/images/icon/icon-03.svg",
    title: "Never spend time updating your CV again",
    description:
      "Your CV is automatically generated by our AI.",
  },
  {
    id: 4,
    icon: "/images/icon/icon-04.svg",
    title: "Deliver diplomas and certificates to your learners in one click",
    description:
      "Deliver trusted credentials to learners. The verification is automated, secured and standardised.",
  },
  {
    id: 5,
    icon: "/images/icon/icon-05.svg",
    title: "Get AI generated feedback on your CVs",
    description:
      "AI will be able to tell you what you should learn next and how to improve your rate/Salary.",
  },
  {
    id: 6,
    icon: "/images/icon/icon-06.svg",
    title: "Get AI feedbacks on the skills of the candidates",
    description:
      "AI will help you identify strenght and weakness of your candidates.",
  },
];

export default featuresData;
